# --- General options --- #
lang: en
title: Racine Ennis
email: racine.ennis@gmail.com
description: "A blog about software and technology"
url: "https://racineennis.ca"
author:
  name: Racine Ennis
  picture: /assets/images/myself.jpg
google_analytics: G-M70Z88X3D0
permalink: "/:year/:month/:day/:title"

github_username: RaySceneNS
logo: /assets/icons/logo.svg

#Search settings
search: true
search_full_content: true
search_provider: lunr

#Disqus settings
disqus:
  shortname: racineennis-ca

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: "/page:num/"

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: false